main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('posts/<slug:product_slug>/', views.post_details, name='post-details'),
    path('add-post/', views.add_post, name='add-post'),
    path('setup-site/', views.setup_site, name='setup-site'),
    path('action-handler/', views.action_handler, name='action-handler'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from account.models import Profile


class Location(models.Model):
    LOCATION_CHOICES = [
        ('division', 'Division'),
        ('district', 'District'),
        ('thana', 'Thana'),
        ('city', 'City'),
    ]

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=10, choices=LOCATION_CHOICES)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField(
        upload_to="main/categories")

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CONDITION_CHOICES = [
        ('used', 'Used'),
        ('new', 'New')
    ]

    title = models.CharField(max_length=500)
    slug = models.SlugField(blank=True)
    description = models.TextField()
    price = models.FloatField()
    is_negotiable = models.BooleanField(default=False)
    condition = models.CharField(max_length=10, choices=CONDITION_CHOICES)
    contact = models.CharField(max_length=50)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    sub_category = models.ForeignKey(
        SubCategory, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Photo(models.Model):
    file = models.ImageField(upload_to='main/products')
    is_primary = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title


class SiteInfo(models.Model):
    name = models.CharField(max_length=20)
    tagline = models.CharField(max_length=50)
    sub_tagline = models.CharField(max_length=250)
    logo = models.ImageField(upload_to='main/sites')
    address = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    contact = models.CharField(max_length=50)
    facebook = models.CharField(max_length=50)
    instagram = models.CharField(max_length=50)
    youtube = models.CharField(max_length=50)

main/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.db.models import Q
from django.views.generic import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from main.models import *
from account.models import *


def home(request):
    if request.method == 'GET':
        all_category = Category.objects.all()

        context = {
            "categories": all_category,
        }
        return render(request, 'main/home.html', context)


def posts(request):
    cities = Location.objects.filter(type='city')
    divisions = Location.objects.filter(type='division')

    context = {
        'cities': cities,
        'divisions': divisions
    }

    if 'sub_category' in request.GET:
        id = request.GET.get('sub_category')
        sub_category = SubCategory.objects.get(
            id=id)
        products = Product.objects.filter(
            sub_category=sub_category).order_by('-created_at')

        page = request.GET.get('page', 1)
        paginator = Paginator(products, 5)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        snip = '&sub_category={}'.format(id)

        context['products'] = products
        context['snip'] = snip

    elif 'category' in request.GET:
        id = request.GET.get('category')
        category = Category.objects.get(id=id)
        products = Product.objects.filter(
            sub_category__category=category).order_by('-created_at')

        page = request.GET.get('page', 1)
        paginator = Paginator(products, 5)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        snip = '&category={}'.format(id)

        context['products'] = products
        context['snip'] = snip

    elif 'userid' in request.GET:
        user_id = request.GET['userid']
        products = Product.objects.filter(seller_id=user_id)

        context['products'] = products

    else:
        products = Product.objects.all().order_by('-created_at')
        page = request.GET.get('page', 1)
        paginator = Paginator(products, 5)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context['products'] = products

    return render(request, 'main/posts.html', context)


def post_details(request, product_slug):
    try:
        product = Product.objects.get(slug=product_slug)
        product.views = product.views + 1
        product.save()

        context = {
            'product': product
        }
        return render(request, 'main/details.html', context)
    except Product.DoesNotExist:
        raise Http404


# def c_signup(request):
#     # if request == 'GET': Otp confirmation part backend i did not solved.
#     return render(request, 'main/signup-confirm.html')

#     if request.method == 'POST':
#         # otp = request.POST['otp'] This time we dont need otp.
#         password = request.POST['password']
#         c__password = request.POST['c__password']

#         nxt_customer = Customer_details(
#             password=password, c_password=c__password)
#         nxt_customer.save()
#         return redirect('/')


@login_required(login_url='/login')
def action_handler(request):
    action = request.GET.get('action')

    if action == 'get-subcategory':
        category_id = request.GET.get('id')
        subcategories = SubCategory.objects.filter(category_id=category_id)
        subcategory_list = list(subcategories.values())

        return JsonResponse(subcategory_list, safe=False)

    elif action == 'get-areas':
        location_id = request.GET.get('id')
        areas = Location.objects.filter(parent_id=location_id)
        area_list = list(areas.values())

        return JsonResponse(area_list, safe=False)


@login_required(login_url='/login')
def add_post(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        price = request.POST.get("price")
        is_negotiable = True if request.POST.get("negotiable") == 'on' else False
        condition = request.POST.get('condition')
        photos = request.FILES.getlist('files')
        subcategory = SubCategory.objects.get(id=request.POST.get("subcategory"))
        phone = request.POST.get("phone")
        location = Location.objects.get(id=request.POST.get('area'))

        product = Product.objects.create(title=title, sub_category=subcategory, condition=condition, contact=phone, price=price, description=description,
                                         is_negotiable=is_negotiable, location=location, seller=request.user)

        is_primary = True
        for photo in photos:
            Photo.objects.create(
                file=photo, product=product, is_primary=is_primary)
            is_primary = False
        return redirect("/")

    else:
        categories = Category.objects.all()
        locations = Location.objects.filter(
            Q(type="city") | Q(type="division")).distinct()
        context = {
            'categories': categories,
            'locations': locations,
        }

        return render(request, 'main/addposts.html', context)


def setup_site(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        tagline = request.POST.get('tagline')
        email = request.POST.get('email')
        address = request.POST.get('address')
        contact = request.POST.get('contact')
        SiteInfo.objects.create(name=name, tagline=tagline, email=email,
                                address=address, contact=contact)

        return redirect('/')


def not_found(request):
    return render(request, 'main/404.html')


def handler404(request, exception):
    return render(request, 'main/404.html', status=404)

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'main/partials/meta.html' %}

    {% block meta %}
    {% endblock %}

    {% include 'main/partials/styles.html' %}

    {% block styles %}
    {% endblock %}
</head>

{% if site_info %}

<body>
    {% include 'main/partials/navbar.html' %}

    {% block body %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    {% include 'main/partials/scripts.html' %}

    {% block scripts %}
    {% endblock %}
</body>
{% else %}
{% include 'main/setup.html' %}
{% endif %}

</html>

main/templates/main/details.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<title>{{ product.title }} | {{ site_info.name }}</title>
{% endblock %}


{% block styles %}
<style>
    .btn-lg {
        font-size: 19px;
    }
</style>
{% endblock %}

{% block body %}
<div class="wrapper py-1 product-detail">
    <div class="container-fluid">
        <div class="d-flex flex-row py-2" id="details">
            <div class="col-lg-8" id="details-body">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="d-flex justify-content-between m-1">
                            <div>
                                <h5 style="font-weight: 800;">{{ product.title }}</h5>
                                <small>
                                    <span class="mr-4"><i
                                            class="fas fa-map-marker-alt mr-1"></i>{{ product.location.name }}</span>
                                    <span class="mr-4"><i class="far fa-clock mr-1"></i>{{ product.created_at }}</span>
                                    <span><i class="far fa-eye mr-1"></i>{{ product.views }}</span>
                                </small>
                                <div class="d-flex align-items-center sharer">
                                    <div class="mr-1">Share:</div>
                                    <a href="https://www.facebook.com/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="d-inline-block media"><i class="fab fa-facebook-f"></i></a>
                                    <a href="https://www.twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text=Checkout {{ product.title }} via {{ site_info.name }}" target="_blank" class="d-inline-block media"><i class="fab fa-twitter"></i></a>
                                </div>
                            </div>
                            <div class="pricing">
                                <small class="text-red"
                                    style="font-weight: 700; font-size: 1.5em; color: hsl(0, 88%, 68%);">Tk
                                    {{ product.price }}</small>
                                <p class="text-right">{% if product.is_negotiable %}Negotiable {% else %} Fixed
                                    {% endif %}</p>
                            </div>
                        </div>
                        <div class="thumbnail-wrapper">
                            {% for photo in product.photo_set.all %}
                            {% if photo.is_primary %}
                            <img src="{% get_media_prefix %}{{ photo.file }}" alt="{{ product.title }}"
                                class="img-fluid rounded">
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="card my-3">
                    <div class="card-body detail-content">
                        <div class="mb-2 info">
                            <div class="d-flex">
                                <h6 class="sub-heading">Condition:</h6>
                                <small class="ml-2">
                                    {% if product.condition == 'used' %}
                                    Used
                                    {% elif product.condition == 'new' %}
                                    New
                                    {% endif %}
                                </small>
                            </div>
                        </div>
                        <hr>
                        <div>
                            <h6 class="sub-heading">Description:</h6>
                            <div class="description">{{ product.description}}</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-11" id="details-user">
                <div class="card my-3">
                    <div class="card-body text-center">
                        <div class="text-center">
                            {% if product.seller.profile.avatar %}
                            <img src="{% get_media_prefix %}{{ product.seller.profile.avatar }}"
                                alt="{{ product.seller.username }}">
                            {% else %}
                            <img src="{% static '/img/default-user-avatar.jpg' %}" alt="">
                            {% endif %}
                        </div>
                        <small class="d-inline-block pt-1">For sale by</small>
                        <h6 style="font-weight: 800; font-size: .95em;">{{ product.seller.first_name }}
                            {{ product.seller.last_name }}</h6>
                        <hr>
                        <div class="d-flex justify-content-center">
                            <div class="flex-1">
                                <button class="btn btn-danger btn-lg mr-2">
                                    <i class="fas fa-phone mr-2"></i>{{ product.contact }}
                                </button>
                            </div>
                            <div class="flex-1">
                                <a href="/posts/?userid={{ product.seller.id }}" class="btn btn-light btn-lg">View all
                                    ads</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card my-3">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="w-100">
                                <div class="alert alert-warning">
                                    Safety Tips
                                </div>
                                <ul class="list-unstyled pl-1" style="font-size: 15px">
                                    <li>Meet seller at a safe location</li>
                                    <li>Check the item before you buy</li>
                                    <li>Pay only after collecting item</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {


    });
</script>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %} {% load static %} {% block meta %}
<title>{{ site_info.name }} | {{ site_info.tagline }}</title>
{% endblock %} {% block body %}
<section class="hero sp-80">
  <div class="container-fluid">
    <div class="hero-content-wrapper">
      <h1 class="title">{{ site_info.tagline }}</h1>
      <p class="subtitle">
        {{ site_info.sub_tagline }}
      </p>
      <div class="row">
        <div class="col-md-9 mx-auto mt-4">
          {% include 'main/partials/search.html' %}
        </div>
      </div>
    </div>
    <div class="featured-category mt-4 pt-2 mx-5">
      <div class="d-flex justify-content-center">
        {% for category in categories %} {% if forloop.counter0 < 9 %}
        <a href="/posts/?category={{ category.id }}" class="mx-2">
          <div class="featured-category-item">
            <div class="img">
              <img src="{% get_media_prefix %}{{ category.thumbnail }}" alt="category" class="img-fluid" />
            </div>
            <p>{{ category.name }}</p>
          </div>
        </a>
        {% endif %} {% endfor %}
      </div>
    </div>
  </div>
</section>

<section class="py-4 categories">
  <div class="container">
    <h5 class="title">All Categories</h5>
    <div class="row no-gutters">
      {% for category in categories %}
      <div class="col-md-4 mb-3">
        <div class="p-4 h-100 item">
          <div class="row">
            <div class="col-2 img-wrapper">
              <img src="{% get_media_prefix %}{{ category.thumbnail }}" alt="clothings" class="img-fluid" />
            </div>
            <div class="col-10 sub-categories">
              <h6 class="subtitle">
                <a href="/posts/?category={{ category.id }}">{{ category.name }}</a>
              </h6>
              <ul class="list-unstyled m-0">
                {% for sub_category in category.subcategory_set.all %}
                <li><a href="/posts/?sub_category={{ sub_category.id }}" class="subc">{{ sub_category.name }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section class="sp-80 call-to-action">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 text-center">
        <h4>Do you have something to sell?</h4>
        <p>Post your ad on {{ site_info.name }}</p>
        <a href="{% url 'add-post' %}" class="btn ylw-post-btn">Post an ad now!</a>
      </div>
      <div class="col-md-6">
        <img src="{% get_media_prefix %}{{ site_info.logo }}" alt="{{ site_info.name }}"
          class="img-fluid" style="width: 300px" />
      </div>
    </div>
  </div>
</section>
{% endblock %}

main/templates/main/posts.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<title>{{ site_info.name }}</title>
{% endblock %}

{% block body %}
<div class="wrapper py-3 px-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="wrapper">
                    {% include 'main/partials/search.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row py-4" id="post">
            <div class="col-lg-3 col-1" id="post-filter">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-row">
                            <div>
                                <h6>Filter</h6>
                            </div>
                            <div class="ml-auto"><small class="text-red"
                                    style="font-size: .6em; font-weight: 600;">Clear all filters</small></div>
                        </div>
                        <hr class="m--1">
                        <div class="my-3">
                            <h6 style="font-size: .95em;">Sort By</h6>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="all" type="checkbox">
                                <label class="custom-control-label" for="all">
                                    <span>All</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="newest" type="checkbox">
                                <label class="custom-control-label" for="newest">
                                    <span>Newest</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="oldest" type="checkbox">
                                <label class="custom-control-label" for="oldest">
                                    <span>Oldest</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="low-to-high" type="checkbox">
                                <label class="custom-control-label" for="low-to-high">
                                    <span>Price : Low > High</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="high-to-low" type="checkbox">
                                <label class="custom-control-label" for="high-to-low">
                                    <span>Price : High > Low</span>
                                </label>
                            </div>
                        </div>
                        <hr class="m--1">
                        <div class="my-3">
                            <h6 style="font-size: .95em;">Condition</h6>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="all1" type="checkbox">
                                <label class="custom-control-label" for="all1">
                                    <span>All</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="new" type="checkbox">
                                <label class="custom-control-label" for="new">
                                    <span>New</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="used" type="checkbox">
                                <label class="custom-control-label" for="used">
                                    <span>Used</span>
                                </label>
                            </div>
                            <div class="custom-control custom-checkbox mb-1 ml-4">
                                <input class="custom-control-input" id="paid2" type="checkbox">
                                <label class="custom-control-label" for="paid2">
                                    <span>Paid</span>
                                </label>
                            </div>
                        </div>
                        {% comment %} <hr class="m--1">
                        <div class="my-3">
                            <h6 style="font-size: .95em;">Categories</h6>
                            <div class="custom-control mb-1">
                                <a href='#'>All Categories</a>
                            </div>
                            <div class="custom-control mb-1">
                                <a href='#'>Categories Test</a>
                            </div>
                            <div class="custom-control mb-1">
                                <a href='#'>Categories Test</a>
                            </div>
                            <div class="custom-control mb-1">
                                <a href='#'>Categories Test</a>
                            </div>
                            <div class="custom-control mb-1">
                                <a href='#'>Categories Test</a>
                            </div>
                        </div> {% endcomment %}
                        <hr class="m--1">
                        <div class="my-3">
                            <h6 style="font-size: .95em;">Division</h6>
                            {% for division in divisions %}
                            <div class="custom-control mb-1">
                                <a href='#'>{{ division.name }}</a>
                            </div>
                            {% endfor %}
                        </div>
                        <hr class="m--1">
                        <div class="my-3">
                            <h6 style="font-size: .95em;">City</h6>
                            {% for city in cities %}
                            <div class="custom-control mb-1">
                                <a href='#'>{{ city.name }}</a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-11" id="post-item">
                {% if products %}
                {% for product in products %}
                <a href={% url 'post-details' product.slug %}>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="mr-3">
                                    {% for photo in product.photo_set.all %}
                                    {% if photo.is_primary %}
                                    <img src="{% get_media_prefix %}{{ photo.file }}" alt="{{ product.title }}"
                                        class="rounded">
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="d-flex flex-column justify-content-between w-100">
                                    <div>
                                        <h5 class="card-title">{{ product.title }}</h5>
                                        <p style='font-size: .9em; color: hsl(0, 0%, 46%);'>
                                            {{ product.description | truncatewords:20 }}
                                        </p>
                                        <small class='text-danger'
                                            style='font-weight: 700; font-size: 1.1em; color: hsl(0, 88%, 68%);'>Tk
                                            {{ product.price }}</small>
                                    </div>
                                    <div>
                                        <hr />
                                        <small>
                                            <span class="mr-4" style="min-width: 80px; display: inline-block;"><i
                                                    class="fas fa-map-marker-alt mr-1"></i>{{ product.location }}</span>
                                            <span class="mr-4"><i
                                                    class="far fa-clock mr-1"></i>{{ product.created_at }}</span>
                                            <span class="mr-4"><i
                                                    class="fas fa-cube mr-1"></i>{% if product.condition == 'new' %}New
                                                {% else %} Used
                                                {% endif %}</span>
                                            <span><i class="far fa-eye mr-1"></i>{{product.views}}</span>
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
                {% else %}
                <h1 class="mt-3">No Product Found</h1>
                {% endif %}
            </div>

            <div class="container">
                <nav aria-label="Page navigation example">
                    {% if products.has_other_pages %}
                    <ul class="pagination justify-content-center">
                        {% if products.has_previous %}
                        <li class="page-item"><a class="page-link"
                                href="?page={{ products.previous_page_number }}{{ snip }}">&laquo;</a></li>
                        {% else %}
                        <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                        {% endif %}

                        {% for i in products.paginator.page_range %}
                        {% if products.number == i %}
                        <li class="page-item"><span class="page-link">{{ i }} <span
                                    class="sr-only">(current)</span></span></li>
                        {% else %}
                        <li class="page-item"><a href="{% url 'posts' %}?page={{ i }}{{ snip }}"
                                class="page-link">{{ i }}</a></li>
                        {% endif %}
                        {% endfor %}

                        {% if products.has_next %}
                        <li class="page-item"><a href="?page={{ products.next_page_number }}{{ snip }}"
                                class="page-link">&raquo;</a></li>
                        {% else %}
                        <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {


    });
</script>
{% endblock %}